name: containerized-gym-project
services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.prod
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
      - /app/node_modules # Prevents host from overwriting container node_modules 

  db:
    image: mysql:8
    volumes: 
      - todo_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
   
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    ports: 
      - 8080:80
    environment:
      - MY_SQL_USER=slim
      - MY_SQL_PASSWORD=slim:password 
      - MySQL_DB=todos

volumes:
  todo_data:
