FROM node:20-alpine

# ARG mode

# RUN if ["${mode}" = "dev" ]; then echo "Development"; else echo "Production"; fi

WORKDIR /app

COPY package*.json /app

RUN npm ci

COPY --exclude=Dockerfile.dev . .

COPY . /app

EXPOSE 4000

CMD [ "npm", "run", "dev" ]
