FROM node:20-alpine

# ARG mode

# RUN if ["${mode}" = "dev" ]; then echo "Development"; else echo "Production"; fi

WORKDIR /app

COPY package*.json /app

RUN npm install --allow-scripts

COPY . /app

EXPOSE 3000

CMD [ "npm", "run", "dev" ]
